### ISSUE TITLE
Persisting PrivateKey

### ISSUE THREAD

**Issue by thedavedave** [XRPLF/xrpl4j-sample#5]
Thanks very much to the contributors for these samples - they are super useful.

On studying them, I saw that they all created new key pairs for all transactions and was trying to find a way to persist the private key for future transactions on the server.

Looking at xrpl4j.crypto.keys I managed to find a way that seems to work and thought I'd share this in case it helps anyone and also see if the community sees any issues with the approach:

Seed sd = Seed.ed25519Seed();
KeyPair coldWalletKeyPair = sd.deriveKeyPair();

// Persist the private key

UnsignedByteArray unsignedByteArr = coldWalletKeyPair.privateKey().value();
byte writeByteArr[] = unsignedByteArr.toByteArray();

FileTools.writeBytesToFile(writeByteArr, "file.bin");

// Restore the private key

byte readByteArr[] = FileTools.readFileToBytes("file.bin");
PrivateKey privateKey = PrivateKey.of(UnsignedByteArray.of(byteArr));

**Comment by sappenin** [comment]
Hi @thedavedave - thanks for creating this issue. My apologies for making you do this _yet again_, but I think starting a discussion in the xrpl4j repo is probably the best place for this. I would start that discussion myself, but it's best if you initiate. Do you mind trying this over there?

https://github.com/XRPLF/xrpl4j/discussions

**Comment by sappenin** [comment]
Closing this issue in-favor of [this answer](https://github.com/XRPLF/xrpl4j/discussions/428) in xrpl4j discussions.
